# Generated by Django 5.1.5 on 2025-08-18 01:29

import account.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('accumulating_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('kyc_confirmed', models.BooleanField(default=False)),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('withdrawal_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_set', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('asset', models.CharField(max_length=10)),
                ('deposit_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to=account.models.user_directory_path)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('identity_image', models.ImageField(default='default.jpg', upload_to=account.models.user_directory_path)),
                ('identity_type', models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport')], max_length=142)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.CharField(max_length=20)),
                ('withdraw_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='account.account')),
            ],
        ),
    ]
