# Generated by Django 5.1.5 on 2025-07-11 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('acount_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('accumulating_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in-active', 'In-active')], default='in-active', max_length=100)),
                ('kyc_confirmed', models.BooleanField(default=False)),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('withdrawal_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('asset', models.CharField(max_length=5)),
                ('deposit_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='kyc')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('identity_image', models.ImageField(default='default.jpg', upload_to='kyc')),
                ('identity_type', models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_license', 'Drivers License'), ('international_passport', 'International Passport')], max_length=142)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.CharField(max_length=20)),
                ('withdraw_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successul', 'Successful')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
