# Generated by Django 5.1.5 on 2025-08-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_deposit_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='asset',
            new_name='method',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
