# Generated by Django 5.1.5 on 2025-08-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_asset_withdraw_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_set',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('Bank', 'Bank Transfer')], default='BTC', max_length=20),
        ),
    ]
