# Generated by Django 5.1.5 on 2025-08-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_pin_set_alter_withdraw_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='bank_account_name',
            new_name='swift_code',
        ),
    ]
