# Generated by Django 5.1.5 on 2025-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_bank_account_name_withdraw_swift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
