# Generated by Django 5.1.5 on 2025-12-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_pin_set_alter_kyc_identity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_balance',
            new_name='capital',
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('Bank', 'Bank Transfer')], default='BTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='swift_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
