# Generated by Django 5.1.5 on 2026-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_account_balance_account_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
