# Generated by Django 5.1.5 on 2026-01-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_withdraw_bank_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=30)),
                ('s_price', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.CharField(choices=[('', 'Select Method'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('Bank', 'Bank Transfer')], default='', max_length=10),
        ),
    ]
