# Generated by Django 5.1.5 on 2026-01-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_signal_alter_withdraw_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signal',
            new_name='SignalBot',
        ),
    ]
