# Generated by Django 5.1.5 on 2026-01-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_signal_signalbot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalbot',
            old_name='s_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='signalbot',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalbot',
            name='leverage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signalbot',
            name='market_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalbot',
            name='priority_market',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalbot',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
