# Generated by Django 5.1.5 on 2026-01-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_s_price_signalbot_price_signalbot_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalbot',
            name='direct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signalbot',
            name='leverage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
