# Generated by Django 5.1.5 on 2026-01-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_kyc_fax_remove_kyc_full_name_remove_kyc_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
